/**
 * BoldSign API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DocumentCC } from './documentCC';
import { DocumentInfo } from './documentInfo';
import { FormGroup } from './formGroup';
import { RecipientNotificationSettings } from './recipientNotificationSettings';
import { TemplateRole } from './templateRole';
import { TextTagDefinition } from './textTagDefinition';

export class CreateTemplateRequest {
    'title': string;
    'description'?: string | null;
    'documentTitle'?: string | null;
    'documentMessage'?: string | null;
    'files'?: Array<RequestFile> | null;
    'fileUrls'?: Array<string> | null;
    'roles'?: Array<TemplateRole> | null;
    'allowModifyFiles'?: boolean = true;
    'cc'?: Array<DocumentCC> | null;
    'brandId'?: string | null;
    'allowMessageEditing'?: boolean = true;
    'allowNewRoles'?: boolean = true;
    'allowNewFiles'?: boolean = true;
    'enableReassign'?: boolean = true;
    'enablePrintAndAssign'?: boolean = false;
    'enableSigningOrder'?: boolean = false;
    'documentInfo'?: Array<DocumentInfo> | null;
    'useTextTags'?: boolean = false;
    'textTagDefinitions'?: Array<TextTagDefinition> | null;
    'autoDetectFields'?: boolean = false;
    'onBehalfOf'?: string | null;
    'labels'?: Array<string> | null;
    'templateLabels'?: Array<string> | null;
    'recipientNotificationSettings'?: RecipientNotificationSettings;
    'formGroups'?: Array<FormGroup> | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "documentTitle",
            "baseName": "documentTitle",
            "type": "string"
        },
        {
            "name": "documentMessage",
            "baseName": "documentMessage",
            "type": "string"
        },
        {
            "name": "files",
            "baseName": "files",
            "type": "Array<RequestFile>"
        },
        {
            "name": "fileUrls",
            "baseName": "fileUrls",
            "type": "Array<string>"
        },
        {
            "name": "roles",
            "baseName": "roles",
            "type": "Array<TemplateRole>"
        },
        {
            "name": "allowModifyFiles",
            "baseName": "allowModifyFiles",
            "type": "boolean"
        },
        {
            "name": "cc",
            "baseName": "cc",
            "type": "Array<DocumentCC>"
        },
        {
            "name": "brandId",
            "baseName": "brandId",
            "type": "string"
        },
        {
            "name": "allowMessageEditing",
            "baseName": "allowMessageEditing",
            "type": "boolean"
        },
        {
            "name": "allowNewRoles",
            "baseName": "allowNewRoles",
            "type": "boolean"
        },
        {
            "name": "allowNewFiles",
            "baseName": "allowNewFiles",
            "type": "boolean"
        },
        {
            "name": "enableReassign",
            "baseName": "enableReassign",
            "type": "boolean"
        },
        {
            "name": "enablePrintAndAssign",
            "baseName": "enablePrintAndAssign",
            "type": "boolean"
        },
        {
            "name": "enableSigningOrder",
            "baseName": "enableSigningOrder",
            "type": "boolean"
        },
        {
            "name": "documentInfo",
            "baseName": "documentInfo",
            "type": "Array<DocumentInfo>"
        },
        {
            "name": "useTextTags",
            "baseName": "useTextTags",
            "type": "boolean"
        },
        {
            "name": "textTagDefinitions",
            "baseName": "textTagDefinitions",
            "type": "Array<TextTagDefinition>"
        },
        {
            "name": "autoDetectFields",
            "baseName": "autoDetectFields",
            "type": "boolean"
        },
        {
            "name": "onBehalfOf",
            "baseName": "onBehalfOf",
            "type": "string"
        },
        {
            "name": "labels",
            "baseName": "labels",
            "type": "Array<string>"
        },
        {
            "name": "templateLabels",
            "baseName": "templateLabels",
            "type": "Array<string>"
        },
        {
            "name": "recipientNotificationSettings",
            "baseName": "recipientNotificationSettings",
            "type": "RecipientNotificationSettings"
        },
        {
            "name": "formGroups",
            "baseName": "formGroups",
            "type": "Array<FormGroup>"
        }    ];

    static getAttributeTypeMap() {
        return CreateTemplateRequest.attributeTypeMap;
    }
}

