/**
 * BoldSign API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { IdVerification } from './idVerification';
import { PhoneNumberWebhookModel } from './phoneNumberWebhookModel';
import { SignerAuthenticationSettings } from './signerAuthenticationSettings';

export class DocumentSignerWebhookModel {
    'signerName'?: string | null;
    'signerRole'?: string | null;
    'signerEmail'?: string | null;
    'phoneNumber'?: PhoneNumberWebhookModel;
    'status'?: DocumentSignerWebhookModel.StatusEnum;
    'enableAccessCode'?: boolean;
    'isAuthenticationFailed'?: boolean | null;
    'enableEmailOTP'?: boolean;
    'isDeliveryFailed'?: boolean;
    'isViewed'?: boolean;
    'order'?: number;
    'signerType'?: string | null;
    'isReassigned'?: boolean;
    'reassignMessage'?: string | null;
    'declineMessage'?: string | null;
    'lastActivityDate'?: Date | null;
    'authenticationType'?: string | null;
    'idVerification'?: IdVerification;
    'allowFieldConfiguration'?: boolean;
    'lastReminderSentOn'?: Date | null;
    'authenticationRetryCount'?: number | null;
    'authenticationSettings'?: SignerAuthenticationSettings;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "signerName",
            "baseName": "signerName",
            "type": "string"
        },
        {
            "name": "signerRole",
            "baseName": "signerRole",
            "type": "string"
        },
        {
            "name": "signerEmail",
            "baseName": "signerEmail",
            "type": "string"
        },
        {
            "name": "phoneNumber",
            "baseName": "phoneNumber",
            "type": "PhoneNumberWebhookModel"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "DocumentSignerWebhookModel.StatusEnum"
        },
        {
            "name": "enableAccessCode",
            "baseName": "enableAccessCode",
            "type": "boolean"
        },
        {
            "name": "isAuthenticationFailed",
            "baseName": "isAuthenticationFailed",
            "type": "boolean"
        },
        {
            "name": "enableEmailOTP",
            "baseName": "enableEmailOTP",
            "type": "boolean"
        },
        {
            "name": "isDeliveryFailed",
            "baseName": "isDeliveryFailed",
            "type": "boolean"
        },
        {
            "name": "isViewed",
            "baseName": "isViewed",
            "type": "boolean"
        },
        {
            "name": "order",
            "baseName": "order",
            "type": "number"
        },
        {
            "name": "signerType",
            "baseName": "signerType",
            "type": "string"
        },
        {
            "name": "isReassigned",
            "baseName": "isReassigned",
            "type": "boolean"
        },
        {
            "name": "reassignMessage",
            "baseName": "reassignMessage",
            "type": "string"
        },
        {
            "name": "declineMessage",
            "baseName": "declineMessage",
            "type": "string"
        },
        {
            "name": "lastActivityDate",
            "baseName": "lastActivityDate",
            "type": "Date"
        },
        {
            "name": "authenticationType",
            "baseName": "authenticationType",
            "type": "string"
        },
        {
            "name": "idVerification",
            "baseName": "idVerification",
            "type": "IdVerification"
        },
        {
            "name": "allowFieldConfiguration",
            "baseName": "allowFieldConfiguration",
            "type": "boolean"
        },
        {
            "name": "lastReminderSentOn",
            "baseName": "lastReminderSentOn",
            "type": "Date"
        },
        {
            "name": "authenticationRetryCount",
            "baseName": "authenticationRetryCount",
            "type": "number"
        },
        {
            "name": "authenticationSettings",
            "baseName": "authenticationSettings",
            "type": "SignerAuthenticationSettings"
        }    ];

    static getAttributeTypeMap() {
        return DocumentSignerWebhookModel.attributeTypeMap;
    }
}

export namespace DocumentSignerWebhookModel {
    export enum StatusEnum {
        None = <any> 'None',
        NotCompleted = <any> 'NotCompleted',
        Completed = <any> 'Completed',
        Declined = <any> 'Declined',
        Revoked = <any> 'Revoked',
        Expired = <any> 'Expired'
    }
}
