/**
 * BoldSign API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DocumentCcWebhookModel } from './documentCcWebhookModel';
import { DocumentSender } from './documentSender';
import { DocumentSignerWebhookModel } from './documentSignerWebhookModel';

export class DocumentEvent {
    'object'?: string | null;
    'documentId'?: string | null;
    'messageTitle'?: string | null;
    'documentDescription'?: string | null;
    'status'?: DocumentEvent.StatusEnum;
    'senderDetail'?: DocumentSender;
    'signerDetails'?: Array<DocumentSignerWebhookModel> | null;
    'ccDetails'?: Array<DocumentCcWebhookModel> | null;
    'onBehalfOf'?: string | null;
    'createdDate'?: Date | null;
    'expiryDate'?: Date | null;
    'enableSigningOrder'?: boolean;
    'disableEmails'?: boolean;
    'revokeMessage'?: string | null;
    'errorMessage'?: string | null;
    'labels'?: Array<string> | null;
    'isCombinedAudit'?: boolean;
    'brandId'?: string | null;
    'documentDownloadOption'?: string | null;
    'metaData'?: { [key: string]: string | null; } | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string"
        },
        {
            "name": "documentId",
            "baseName": "documentId",
            "type": "string"
        },
        {
            "name": "messageTitle",
            "baseName": "messageTitle",
            "type": "string"
        },
        {
            "name": "documentDescription",
            "baseName": "documentDescription",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "DocumentEvent.StatusEnum"
        },
        {
            "name": "senderDetail",
            "baseName": "senderDetail",
            "type": "DocumentSender"
        },
        {
            "name": "signerDetails",
            "baseName": "signerDetails",
            "type": "Array<DocumentSignerWebhookModel>"
        },
        {
            "name": "ccDetails",
            "baseName": "ccDetails",
            "type": "Array<DocumentCcWebhookModel>"
        },
        {
            "name": "onBehalfOf",
            "baseName": "onBehalfOf",
            "type": "string"
        },
        {
            "name": "createdDate",
            "baseName": "createdDate",
            "type": "Date"
        },
        {
            "name": "expiryDate",
            "baseName": "expiryDate",
            "type": "Date"
        },
        {
            "name": "enableSigningOrder",
            "baseName": "enableSigningOrder",
            "type": "boolean"
        },
        {
            "name": "disableEmails",
            "baseName": "disableEmails",
            "type": "boolean"
        },
        {
            "name": "revokeMessage",
            "baseName": "revokeMessage",
            "type": "string"
        },
        {
            "name": "errorMessage",
            "baseName": "errorMessage",
            "type": "string"
        },
        {
            "name": "labels",
            "baseName": "labels",
            "type": "Array<string>"
        },
        {
            "name": "isCombinedAudit",
            "baseName": "isCombinedAudit",
            "type": "boolean"
        },
        {
            "name": "brandId",
            "baseName": "brandId",
            "type": "string"
        },
        {
            "name": "documentDownloadOption",
            "baseName": "documentDownloadOption",
            "type": "string"
        },
        {
            "name": "metaData",
            "baseName": "metaData",
            "type": "{ [key: string]: string | null; }"
        }    ];

    static getAttributeTypeMap() {
        return DocumentEvent.attributeTypeMap;
    }
}

export namespace DocumentEvent {
    export enum StatusEnum {
        InProgress = <any> 'InProgress',
        Completed = <any> 'Completed',
        Declined = <any> 'Declined',
        Expired = <any> 'Expired',
        Revoked = <any> 'Revoked',
        Draft = <any> 'Draft',
        Scheduled = <any> 'Scheduled'
    }
}
