/**
 * BoldSign API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Font {
    'name'?: Font.NameEnum;
    'color'?: string | null;
    'size'?: number;
    'style'?: Font.StyleEnum;
    'lineHeight'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "Font.NameEnum"
        },
        {
            "name": "color",
            "baseName": "color",
            "type": "string"
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "number"
        },
        {
            "name": "style",
            "baseName": "style",
            "type": "Font.StyleEnum"
        },
        {
            "name": "lineHeight",
            "baseName": "lineHeight",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Font.attributeTypeMap;
    }
}

export namespace Font {
    export enum NameEnum {
        Helvetica = <any> 'Helvetica',
        Courier = <any> 'Courier',
        TimesRoman = <any> 'TimesRoman',
        NotoSans = <any> 'NotoSans'
    }
    export enum StyleEnum {
        Regular = <any> 'Regular',
        Bold = <any> 'Bold',
        Italic = <any> 'Italic',
        Underline = <any> 'Underline'
    }
}
