/**
 * BoldSign API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DocumentSender } from './documentSender';
import { DocumentSignerWebhookModel } from './documentSignerWebhookModel';

export class IdentityVerificationEvent {
    'object'?: string | null;
    'documentId'?: string | null;
    'messageTitle'?: string | null;
    'documentDescription'?: string | null;
    'status'?: IdentityVerificationEvent.StatusEnum;
    'senderDetail'?: DocumentSender;
    'signerDetail'?: DocumentSignerWebhookModel;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string"
        },
        {
            "name": "documentId",
            "baseName": "documentId",
            "type": "string"
        },
        {
            "name": "messageTitle",
            "baseName": "messageTitle",
            "type": "string"
        },
        {
            "name": "documentDescription",
            "baseName": "documentDescription",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "IdentityVerificationEvent.StatusEnum"
        },
        {
            "name": "senderDetail",
            "baseName": "senderDetail",
            "type": "DocumentSender"
        },
        {
            "name": "signerDetail",
            "baseName": "signerDetail",
            "type": "DocumentSignerWebhookModel"
        }    ];

    static getAttributeTypeMap() {
        return IdentityVerificationEvent.attributeTypeMap;
    }
}

export namespace IdentityVerificationEvent {
    export enum StatusEnum {
        InProgress = <any> 'InProgress',
        Completed = <any> 'Completed',
        Declined = <any> 'Declined',
        Expired = <any> 'Expired',
        Revoked = <any> 'Revoked',
        Draft = <any> 'Draft',
        Scheduled = <any> 'Scheduled'
    }
}
