/**
 * BoldSign API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { NotificationSettings } from './notificationSettings';

export class SenderIdentityViewModel {
    'name'?: string | null;
    'email'?: string | null;
    'status'?: string | null;
    'createdBy'?: string | null;
    'approvedDate'?: string | null;
    'notificationSettings'?: NotificationSettings;
    'brandId'?: string | null;
    'redirectUrl'?: string | null;
    'metaData'?: { [key: string]: string | null; } | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "createdBy",
            "baseName": "createdBy",
            "type": "string"
        },
        {
            "name": "approvedDate",
            "baseName": "approvedDate",
            "type": "string"
        },
        {
            "name": "notificationSettings",
            "baseName": "notificationSettings",
            "type": "NotificationSettings"
        },
        {
            "name": "brandId",
            "baseName": "brandId",
            "type": "string"
        },
        {
            "name": "redirectUrl",
            "baseName": "redirectUrl",
            "type": "string"
        },
        {
            "name": "metaData",
            "baseName": "metaData",
            "type": "{ [key: string]: string | null; }"
        }    ];

    static getAttributeTypeMap() {
        return SenderIdentityViewModel.attributeTypeMap;
    }
}

