/**
 * BoldSign API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TemplateCcWebhookModel } from './templateCcWebhookModel';
import { TemplateSender } from './templateSender';
import { TemplateSigner } from './templateSigner';

export class TemplateEvent {
    'object'?: string | null;
    'templateId'?: string | null;
    'allowNewFiles'?: boolean | null;
    'allowModifyFiles'?: boolean | null;
    'senderDetail'?: TemplateSender;
    'ccDetails'?: Array<TemplateCcWebhookModel> | null;
    'createdDate'?: Date | null;
    'activityDate'?: Date | null;
    'activityBy'?: string | null;
    'messageTitle'?: string | null;
    'status'?: TemplateEvent.StatusEnum;
    'signerDetails'?: Array<TemplateSigner> | null;
    'enableSigningOrder'?: boolean;
    'templateName'?: string | null;
    'templateDescription'?: string | null;
    'errorMessage'?: string | null;
    'isTemplate'?: boolean = false;
    'brandId'?: string | null;
    'onBehalfOf'?: string | null;
    'labels'?: Array<string> | null;
    'templateLabels'?: Array<string> | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string"
        },
        {
            "name": "templateId",
            "baseName": "templateId",
            "type": "string"
        },
        {
            "name": "allowNewFiles",
            "baseName": "allowNewFiles",
            "type": "boolean"
        },
        {
            "name": "allowModifyFiles",
            "baseName": "allowModifyFiles",
            "type": "boolean"
        },
        {
            "name": "senderDetail",
            "baseName": "senderDetail",
            "type": "TemplateSender"
        },
        {
            "name": "ccDetails",
            "baseName": "ccDetails",
            "type": "Array<TemplateCcWebhookModel>"
        },
        {
            "name": "createdDate",
            "baseName": "createdDate",
            "type": "Date"
        },
        {
            "name": "activityDate",
            "baseName": "activityDate",
            "type": "Date"
        },
        {
            "name": "activityBy",
            "baseName": "activityBy",
            "type": "string"
        },
        {
            "name": "messageTitle",
            "baseName": "messageTitle",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "TemplateEvent.StatusEnum"
        },
        {
            "name": "signerDetails",
            "baseName": "signerDetails",
            "type": "Array<TemplateSigner>"
        },
        {
            "name": "enableSigningOrder",
            "baseName": "enableSigningOrder",
            "type": "boolean"
        },
        {
            "name": "templateName",
            "baseName": "templateName",
            "type": "string"
        },
        {
            "name": "templateDescription",
            "baseName": "templateDescription",
            "type": "string"
        },
        {
            "name": "errorMessage",
            "baseName": "errorMessage",
            "type": "string"
        },
        {
            "name": "isTemplate",
            "baseName": "isTemplate",
            "type": "boolean"
        },
        {
            "name": "brandId",
            "baseName": "brandId",
            "type": "string"
        },
        {
            "name": "onBehalfOf",
            "baseName": "onBehalfOf",
            "type": "string"
        },
        {
            "name": "labels",
            "baseName": "labels",
            "type": "Array<string>"
        },
        {
            "name": "templateLabels",
            "baseName": "templateLabels",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return TemplateEvent.attributeTypeMap;
    }
}

export namespace TemplateEvent {
    export enum StatusEnum {
        InProgress = <any> 'InProgress',
        Completed = <any> 'Completed',
        Declined = <any> 'Declined',
        Expired = <any> 'Expired',
        Revoked = <any> 'Revoked',
        Draft = <any> 'Draft',
        Scheduled = <any> 'Scheduled'
    }
}
