/**
 * BoldSign API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class WebhookEventMetadata {
    'id'?: string;
    'created'?: Date;
    'eventType'?: WebhookEventMetadata.EventTypeEnum;
    'clientId'?: string | null;
    'environment'?: WebhookEventMetadata.EnvironmentEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date"
        },
        {
            "name": "eventType",
            "baseName": "eventType",
            "type": "WebhookEventMetadata.EventTypeEnum"
        },
        {
            "name": "clientId",
            "baseName": "clientId",
            "type": "string"
        },
        {
            "name": "environment",
            "baseName": "environment",
            "type": "WebhookEventMetadata.EnvironmentEnum"
        }    ];

    static getAttributeTypeMap() {
        return WebhookEventMetadata.attributeTypeMap;
    }
}

export namespace WebhookEventMetadata {
    export enum EventTypeEnum {
        Sent = <any> 'Sent',
        Signed = <any> 'Signed',
        Completed = <any> 'Completed',
        Declined = <any> 'Declined',
        Revoked = <any> 'Revoked',
        Reassigned = <any> 'Reassigned',
        Expired = <any> 'Expired',
        Viewed = <any> 'Viewed',
        AuthenticationFailed = <any> 'AuthenticationFailed',
        DeliveryFailed = <any> 'DeliveryFailed',
        Verification = <any> 'Verification',
        SendFailed = <any> 'SendFailed',
        DraftCreated = <any> 'DraftCreated',
        SenderIdentityCreated = <any> 'SenderIdentityCreated',
        SenderIdentityUpdated = <any> 'SenderIdentityUpdated',
        SenderIdentityDeleted = <any> 'SenderIdentityDeleted',
        SenderIdentityRevoked = <any> 'SenderIdentityRevoked',
        SenderIdentityVerified = <any> 'SenderIdentityVerified',
        SenderIdentityDenied = <any> 'SenderIdentityDenied',
        TemplateCreated = <any> 'TemplateCreated',
        TemplateCreateFailed = <any> 'TemplateCreateFailed',
        TemplateDraftCreated = <any> 'TemplateDraftCreated',
        TemplateSendFailed = <any> 'TemplateSendFailed',
        IdentityVerificationInitiated = <any> 'IdentityVerificationInitiated',
        IdentityVerificationSucceeded = <any> 'IdentityVerificationSucceeded',
        IdentityVerificationFailed = <any> 'IdentityVerificationFailed',
        Reminder = <any> 'Reminder',
        Edited = <any> 'Edited'
    }
    export enum EnvironmentEnum {
        Test = <any> 'Test',
        Live = <any> 'Live'
    }
}
